apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-backend
  labels:
    app: loyalty-system
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loyalty-system
      component: backend
  template:
    metadata:
      labels:
        app: loyalty-system
        component: backend
    spec:
      containers:
      - name: backend
        image: loyalty-backend:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: loyalty-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: loyalty-secrets
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: loyalty-secrets
              key: secret-key
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-frontend
  labels:
    app: loyalty-system
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loyalty-system
      component: frontend
  template:
    metadata:
      labels:
        app: loyalty-system
        component: frontend
    spec:
      containers:
      - name: frontend
        image: loyalty-frontend:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://loyalty-backend:8000/api/v1"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-worker
  labels:
    app: loyalty-system
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loyalty-system
      component: worker
  template:
    metadata:
      labels:
        app: loyalty-system
        component: worker
    spec:
      containers:
      - name: worker
        image: loyalty-worker:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: loyalty-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: loyalty-secrets
              key: redis-url
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        command: ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info"]

---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-backend
  labels:
    app: loyalty-system
    component: backend
spec:
  selector:
    app: loyalty-system
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-frontend
  labels:
    app: loyalty-system
    component: frontend
spec:
  selector:
    app: loyalty-system
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loyalty-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - loyalty.yourcompany.com
    secretName: loyalty-tls
  rules:
  - host: loyalty.yourcompany.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: loyalty-backend
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loyalty-frontend
            port:
              number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loyalty-config
  labels:
    app: loyalty-system
data:
  DATABASE_URL: "mssql+pyodbc://loyalty_user:loyalty_password@sqlserver:1433/loyalty_db?driver=ODBC+Driver+17+for+SQL+Server"
  REDIS_URL: "redis://redis:6379"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"

---
apiVersion: v1
kind: Secret
metadata:
  name: loyalty-secrets
  labels:
    app: loyalty-system
type: Opaque
data:
  # Note: These are base64 encoded placeholder values
  # Replace with actual secrets in production
  database-url: bXNzcWwrUHlvZGJjOi8vbG95YWx0eV91c2VyOmxveWFsdHlfcGFzc3dvcmRAc3Fsc2VydmVyOjE0MzMvbG95YWx0eV9kYj9kcml2ZXI9T0RCQytEcml2ZXIrMTcrZm9yK1NRTStTZXJ2ZXI=
  redis-url: cmVkaXM6Ly9yZWRpczo2Mzc5
  secret-key: Y2hhbmdlLW1lLWFuZC11c2UtZW52aXJvbm1lbnQtdmFyaWFibGVzLWluLXByb2R1Y3Rpb24=
  erp-api-key: Y2hhbmdlLW1lLWFuZC11c2UtZW52aXJvbm1lbnQtdmFyaWFibGVzLWluLXByb2R1Y3Rpb24=
  whatsapp-token: Y2hhbmdlLW1lLWFuZC11c2UtZW52aXJvbm1lbnQtdmFyaWFibGVzLWluLXByb2R1Y3Rpb24=