global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Backend application metrics
  - job_name: 'loyalty-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Frontend metrics (if implemented)
  - job_name: 'loyalty-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'loyalty-metrics'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 10s
    metrics_path: '/api/v1/analytics/performance-metrics'
    params:
      format: ['prometheus']

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Remote write configuration (optional)
remote_write:
  - url: "http://remote-storage:9201/write"

# Remote read configuration (optional)
remote_read:
  - url: "http://remote-storage:9201/read"